/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ViewPanel;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import model.OrderDetail;

/**
 *
 * @author Acer
 */
public class OrderNote extends JDialog{
    
    private OrderDetail orderDetail;
    private OnNoteSavedListener listener;


    public OrderNote(java.awt.Frame parent, OrderDetail orderDetail, OnNoteSavedListener listener) {
        super(parent, true); // true = Modal (Chặn cửa sổ cha)
        
        initComponents();
        this.orderDetail = orderDetail;
        this.listener = listener;

        setupWindow();
        loadData();
        addEvents();
    }
    
    // Constructor phụ (không cần Parent Frame)
    public OrderNote(OrderDetail orderDetail, OnNoteSavedListener listener) {
        this.setModal(true); // Quan trọng
        
        initComponents();
        this.orderDetail = orderDetail;
        this.listener = listener;

        setupWindow();
        loadData();
        addEvents();
    }

    // Constructor mặc định
    public OrderNote() {
        initComponents();
    }

    private void setupWindow() {
        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        this.setTitle("Ghi chú món ăn");
        this.pack(); 
        this.setLocationRelativeTo(null); 
    }

    private void loadData() {
        if (orderDetail != null) {
            // 1. Tên món
            if (orderDetail.getFood() != null) {
                // --- SỬA TÊN BIẾN: jLabel13 ---
                // Thay 'jLabel13' bằng tên cái Label hiển thị Tên món của bạn
                jLabel13.setText(orderDetail.getFood().getFoodName());
                
                // 3. Load ảnh
                loadImage(orderDetail.getFood().getImageURL());
            }

            // 2. Ghi chú cũ
            String currentNote = orderDetail.getNote();
            // --- SỬA TÊN BIẾN: note ---
            // Thay 'note' bằng tên cái JTextArea (ô nhập liệu) của bạn
            note.setText(currentNote == null ? "" : currentNote);
        }
    }
    
    private void loadImage(String linkImage) {
        if (linkImage != null && !linkImage.isEmpty() && (linkImage.startsWith("http"))) {
            try {
                // --- SỬA TÊN BIẾN: jLabel12 ---
                // Thay 'jLabel12' bằng tên cái Label hiển thị Ảnh của bạn
                int w = jLabel12.getWidth() > 0 ? jLabel12.getWidth() : 100; // An toàn nếu width = 0
                int h = jLabel12.getHeight() > 0 ? jLabel12.getHeight() : 70;

                ImageIcon icon = new ImageIcon(new URL(linkImage));
                Image img = icon.getImage().getScaledInstance(w, h, Image.SCALE_SMOOTH);
                jLabel12.setIcon(new ImageIcon(img));
            } catch (Exception e) {
                // Bỏ qua lỗi ảnh
            }
        }
    }

    private void addEvents() {
        // --- SỬA TÊN BIẾN: jPanel10 (Nút Lưu) ---
        // Thay 'jPanel10' bằng tên cái Panel hoặc Button nút "Lưu" của bạn
        jPanel10.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        jPanel10.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                confirmSave();
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                // Đổi màu khi di chuột vào (Bạn có thể đổi mã màu khác)
                jPanel10.setBackground(new Color(0, 153, 51)); 
            }

            @Override
            public void mouseExited(MouseEvent e) {
                // Trả về màu gốc khi chuột đi ra (Màu này phải khớp màu thiết kế ban đầu)
                jPanel10.setBackground(new Color(0, 204, 102)); 
            }
        });
    }

    private void confirmSave() {
        // --- SỬA TÊN BIẾN: note ---
        String content = note.getText().trim(); 

        if (listener != null) {
            listener.onSaveNote(content);
        }
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        note = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 245, 248));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Burger-Shrimp.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 23)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Burger bò");
        jLabel13.setToolTipText("");

        jPanel10.setBackground(new java.awt.Color(237, 128, 50));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Ghi chú");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        note.setBackground(new java.awt.Color(255, 255, 255));
        note.setColumns(20);
        note.setLineWrap(true);
        note.setRows(5);
        note.setWrapStyleWord(true);
        jScrollPane1.setViewportView(note);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea note;
    // End of variables declaration//GEN-END:variables
}
