/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ViewPanel;

import java.awt.Cursor;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import model.Food;
import javax.swing.ImageIcon;
import java.net.URL;
import javax.swing.JOptionPane;
import model.OrderDetail;

public class orderItem extends javax.swing.JPanel {

   private Food food;
    private OnOrderListener listener;


    public orderItem(Food food, OnOrderListener listener) {
        initComponents();
        this.food = food;
        this.listener = listener;
        
        loadData();  // Đổ dữ liệu (Tên, giá, ảnh)
        addEvents(); // Gán sự kiện click
    }

    public orderItem() {
        initComponents();
    }

    // --- HÀM XỬ LÝ LOGIC ---

    private void loadData() {
        if (food != null) {
            // 1. Hiển thị Tên và Giá
            FoodName.setText(food.getFoodName());
            FoodPrice.setText(String.format("%,.0f đ", food.getPrice())); // Format ví dụ: 55,000 đ

            // 2. Xử lý hiển thị Ảnh từ URL (Internet)
            try {
                String linkImage = food.getImageURL();
                
                // Kiểm tra xem link có hợp lệ không (có bắt đầu bằng http/https)
                if (linkImage != null && (linkImage.startsWith("http") || linkImage.startsWith("https"))) {
                    URL url = new URL(linkImage);
                    ImageIcon icon = new ImageIcon(url);
                    
                    // Resize ảnh cho vừa với khung (Width: 140, Height: 90) để giao diện đẹp
                    Image img = icon.getImage().getScaledInstance(140, 90, Image.SCALE_SMOOTH);
                    ImageURL.setIcon(new ImageIcon(img));
                } else {
                    // Nếu không có ảnh hoặc link lỗi thì để trống hoặc set icon mặc định
                    ImageURL.setText("No Image"); 
                }
            } catch (Exception e) {
                System.err.println("Lỗi load ảnh món: " + food.getFoodName());
                ImageURL.setIcon(null); // Set null nếu lỗi mạng
            }
        }
    }

    private void addEvents() {
        MouseAdapter eventMoCuaSo = new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                // [DEBUG] In ra dòng này để biết chuột đã ăn chưa
                System.out.println("Đã click vào món: " + food.getFoodName());

                try {
                    // 1. Tạo OrderDetail giả
                    OrderDetail tempDetail = new OrderDetail(food, 1);
                    
                    // 2. Mở cửa sổ Note
                    OrderNote noteWindow = new OrderNote(tempDetail, new OnNoteSavedListener() {
                        @Override
                        public void onSaveNote(String noteContent) {
                            if (listener != null) {
                                // Gửi dữ liệu đi khi ấn Lưu
                                listener.onAddFood(food, noteContent); 
                            }
                        }
                    });
                    
                    noteWindow.setVisible(true);
                    
                } catch (Exception ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Lỗi mở cửa sổ: " + ex.getMessage());
                }
            }
        };

        // --- GẮN SỰ KIỆN CHO CẢ 2 THÀNH PHẦN ---
        
        // 1. Gắn cho dòng chữ
        btnAddFood.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnAddFood.addMouseListener(eventMoCuaSo);

        // 2. Gắn cho cái hộp màu cam (QUAN TRỌNG)
        jPanel10.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jPanel10.addMouseListener(eventMoCuaSo);
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        ImageURL = new javax.swing.JLabel();
        FoodName = new javax.swing.JLabel();
        FoodPrice = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        btnAddFood = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        ImageURL.setForeground(new java.awt.Color(255, 255, 255));
        ImageURL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImageURL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Burger-Shrimp.png"))); // NOI18N

        FoodName.setBackground(new java.awt.Color(255, 255, 255));
        FoodName.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        FoodName.setForeground(new java.awt.Color(0, 0, 0));
        FoodName.setText("Burger bò");
        FoodName.setToolTipText("");

        FoodPrice.setBackground(new java.awt.Color(255, 255, 255));
        FoodPrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        FoodPrice.setForeground(new java.awt.Color(102, 102, 102));
        FoodPrice.setText("55.000 đ");
        FoodPrice.setToolTipText("");

        jPanel10.setBackground(new java.awt.Color(245, 245, 248));

        btnAddFood.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnAddFood.setForeground(new java.awt.Color(237, 128, 50));
        btnAddFood.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAddFood.setText("Thêm món");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAddFood, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddFood)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ImageURL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(FoodPrice)
                        .addComponent(FoodName, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImageURL, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FoodName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FoodPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FoodName;
    private javax.swing.JLabel FoodPrice;
    private javax.swing.JLabel ImageURL;
    private javax.swing.JLabel btnAddFood;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
