/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ViewPanel;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.ImageIcon;
import model.Account;

/**
 *
 * @author Acer
 */
public class PersonItem extends javax.swing.JPanel {

    private Account account;
    private OnPersonActionListener listener;

    public PersonItem(Account acc, OnPersonActionListener listener) {
        initComponents();
        this.account = acc;
        this.listener = listener;
        
        loadData();
        addEvents();
    }
    
    public PersonItem() {
        initComponents();
    }

    private void loadData() {
        if (account != null) {
            fullname.setText(account.getFullName());
            username.setText("@" + account.getUserName());

            if (account.getStatus() == 0) {
                jPanel2.setBackground(new Color(240, 240, 240)); // Màu xám
                fullname.setForeground(Color.RED);
                fullname.setText(account.getFullName() + " (Đã khóa)");
                btnUpdatePerson.setText("Mở khóa / Sửa");
            } else {
                jPanel2.setBackground(Color.WHITE);
                fullname.setForeground(Color.BLACK);
                btnUpdatePerson.setText("Cập nhật");
            }

            if (account.getRoleName() != null) {
                lblRole.setText(account.getRoleName());
            } else {
                lblRole.setText(account.getRoleID() == 1 ? "Quản lý" : "Nhân viên");
            }

            if (account.getRoleID() == 1) { 
                PnlRole.setBackground(new Color(255, 204, 204)); 
                lblRole.setForeground(Color.RED);
            } else { // Nhân viên
                PnlRole.setBackground(new Color(204, 229, 255)); 
                lblRole.setForeground(Color.BLUE);
            }

            String iconPath = "";
            if (account.getGender() == 1) { // Nam
                iconPath = "/images/male.png"; 
            } else { 
                iconPath = "/images/female.png";
            }
            
            try {
                 java.net.URL imgUrl = getClass().getResource(iconPath);
                 if (imgUrl != null) {
                     ImageIcon icon = new ImageIcon(imgUrl);
                     java.awt.Image img = icon.getImage().getScaledInstance(120, 120, java.awt.Image.SCALE_SMOOTH);
                     imagePerson.setIcon(new ImageIcon(img));
                     imagePerson.setText("");
                 } else {
                     imagePerson.setText(account.getGender() == 1 ? "Nam" : "Nữ");
                 }
            } catch (Exception e) {
                imagePerson.setText("No Image");
            }
        }
    }

    private void addEvents() {
        // Sự kiện nút Cập nhật
        jPanel4.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                if (listener != null) {
                    listener.onEditPerson(account);
                }
            }
            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                jPanel4.setBackground(new Color(230, 230, 230)); 
            }
            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                jPanel4.setBackground(new Color(242, 242, 242)); 
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        fullname = new javax.swing.JLabel();
        imagePerson = new javax.swing.JLabel();
        PnlRole = new javax.swing.JPanel();
        lblRole = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnUpdatePerson = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        username.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        username.setForeground(new java.awt.Color(153, 153, 153));
        username.setText("username");

        fullname.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        fullname.setForeground(new java.awt.Color(0, 0, 0));
        fullname.setText("Tên nhân viên");

        imagePerson.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagePerson.setText("Anhr");

        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRole.setText("jLabel5");

        javax.swing.GroupLayout PnlRoleLayout = new javax.swing.GroupLayout(PnlRole);
        PnlRole.setLayout(PnlRoleLayout);
        PnlRoleLayout.setHorizontalGroup(
            PnlRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRole, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
        );
        PnlRoleLayout.setVerticalGroup(
            PnlRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRole, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        btnUpdatePerson.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnUpdatePerson.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUpdatePerson.setText("jLabel7");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnUpdatePerson, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnUpdatePerson, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagePerson, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(PnlRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username)
                            .addComponent(fullname))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(fullname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(username)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PnlRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addComponent(imagePerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlRole;
    private javax.swing.JLabel btnUpdatePerson;
    private javax.swing.JLabel fullname;
    private javax.swing.JLabel imagePerson;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
